# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: "ubuntu-latest"
  #name: "COMP367-Docker"

steps:
- script: |
    sudo apt update
    sudo apt install -y maven
    mvn -version
  displayName: 'Install Maven'

- script: mvn -version
  displayName: 'Check Maven Version'
  
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/surefire-reports/*.xml'
    
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: 'target/site/jacoco/jacoco.xml'
    pathToSources: 'src/main/java/com/training/example/jacocoexample'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/target'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'spring-petclinic'
    publishLocation: 'Container'

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'training-feed'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'deploy'
    options: '-DskipTests'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenAuthenticateFeed: false # This is key
    
